cd C:.Users.vm.Documents.GitHub

python.exe C:\Python27\Lib\pydoc.py -w hystck.common
python.exe C:\Python27\Lib\pydoc.py -w hystck.common.browser
python.exe C:\Python27\Lib\pydoc.py -w hystck.common.config
python.exe C:\Python27\Lib\pydoc.py -w hystck.common.constants
python.exe C:\Python27\Lib\pydoc.py -w hystck.common.exceptions
python.exe C:\Python27\Lib\pydoc.py -w hystck.common.ipaddr
python.exe C:\Python27\Lib\pydoc.py -w hystck.common.macAddr
python.exe C:\Python27\Lib\pydoc.py -w hystck.common.mailer
python.exe C:\Python27\Lib\pydoc.py -w hystck.common.network
python.exe C:\Python27\Lib\pydoc.py -w hystck.core
python.exe C:\Python27\Lib\pydoc.py -w hystck.core.vm
python.exe C:\Python27\Lib\pydoc.py -w hystck.core.vmHelper
python.exe C:\Python27\Lib\pydoc.py -w hystck.examples.destroyNetworks
python.exe C:\Python27\Lib\pydoc.py -w hystck.examples.hystckmanager
python.exe C:\Python27\Lib\pydoc.py -w hystck.examples.interaktionsmanagerWindows
python.exe C:\Python27\Lib\pydoc.py -w hystck.examples.setupNetworks
python.exe C:\Python27\Lib\pydoc.py -w hystck.examples
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager.linux
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager.linux.interactionManager
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager.linux.xaut
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager.windows.inputDevice.utilities
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager.windows.inputDevice.utilities._sendkeys
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager.windows.inputDevice.utilities.seleniumkeys
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager.windows.inputDevice.utilities.SendKeys
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager.windows.inputDevice.utilities
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager.windows.inputDevice
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager.windows.inputDevice.inputDevice
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager.windows.inputDevice.keyboard
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager.windows.inputDevice.mouse
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager.windows
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager.windows.application
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager.windows.application.application
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager.windows.application.instantMessenger
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager.windows.application.mailClient
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager.windows.application.webBrowser
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager.windows.application
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager.windows.interactionmanager
python.exe C:\Python27\Lib\pydoc.py -w hystck.interactionManager.windows.window
python.exe C:\Python27\Lib\pydoc.py -w hystck